# Dockerfile-nginx
FROM nginx:latest

# Nginx will listen on this port
EXPOSE 80

# Remove the default config file that
# /etc/nginx/nginx.conf includes
RUN rm /etc/nginx/conf.d/default.conf

# We copy the custom nginx config file in order to
# use uwsgi webserver and route traffic through nginx
COPY uwsgi.conf /etc/nginx/conf.d
